import type {
  Activity,
  Category,
  DashboardStats,
  MonitoringMetrics,
  Product,
  Sale,
  Supplier,
} from "@/types/inventory";

export const categories: Category[] = [
  {
    id: "cat-1",
    name: "Electronics",
    description: "Gadgets, devices, and accessories",
    productCount: 48,
    color: "#6366f1",
  },
  {
    id: "cat-2",
    name: "Clothing",
    description: "Apparel and fashion items",
    productCount: 72,
    color: "#8b5cf6",
  },
  {
    id: "cat-3",
    name: "Food & Beverage",
    description: "Consumables and drinks",
    productCount: 35,
    color: "#06b6d4",
  },
  {
    id: "cat-4",
    name: "Office Supplies",
    description: "Stationery and office equipment",
    productCount: 29,
    color: "#10b981",
  },
  {
    id: "cat-5",
    name: "Home & Garden",
    description: "Furniture and decor",
    productCount: 41,
    color: "#f59e0b",
  },
];

export const suppliers: Supplier[] = [
  {
    id: "sup-1",
    name: "TechGlobal Inc.",
    email: "orders@techglobal.com",
    phone: "+1 (555) 123-4567",
    address: "123 Silicon Valley, CA",
    rating: 4.8,
    productCount: 32,
  },
  {
    id: "sup-2",
    name: "FashionHub Co.",
    email: "contact@fashionhub.com",
    phone: "+1 (555) 234-5678",
    address: "456 Fashion Ave, NY",
    rating: 4.5,
    productCount: 45,
  },
  {
    id: "sup-3",
    name: "FreshMart Supply",
    email: "supply@freshmart.com",
    phone: "+1 (555) 345-6789",
    address: "789 Market St, TX",
    rating: 4.2,
    productCount: 28,
  },
  {
    id: "sup-4",
    name: "OfficePro Ltd.",
    email: "sales@officepro.com",
    phone: "+1 (555) 456-7890",
    address: "321 Business Blvd, IL",
    rating: 4.6,
    productCount: 19,
  },
];

export const products: Product[] = [
  {
    id: "prod-1",
    name: "Wireless Bluetooth Headphones",
    sku: "WBH-001",
    categoryId: "cat-1",
    supplierId: "sup-1",
    price: 79.99,
    cost: 45.0,
    quantity: 156,
    minStock: 20,
    status: "in_stock",
    description: "Premium noise-cancelling wireless headphones",
    image: "🎧",
    createdAt: "2025-11-15",
  },
  {
    id: "prod-2",
    name: "Smart Watch Pro",
    sku: "SWP-002",
    categoryId: "cat-1",
    supplierId: "sup-1",
    price: 299.99,
    cost: 180.0,
    quantity: 8,
    minStock: 15,
    status: "low_stock",
    description: "Advanced fitness tracking smartwatch",
    image: "⌚",
    createdAt: "2025-10-20",
  },
  {
    id: "prod-3",
    name: "Cotton T-Shirt (Pack of 3)",
    sku: "CTS-003",
    categoryId: "cat-2",
    supplierId: "sup-2",
    price: 34.99,
    cost: 15.0,
    quantity: 320,
    minStock: 50,
    status: "in_stock",
    description: "100% organic cotton t-shirts",
    image: "👕",
    createdAt: "2025-12-01",
  },
  {
    id: "prod-4",
    name: "Denim Jeans",
    sku: "DJN-004",
    categoryId: "cat-2",
    supplierId: "sup-2",
    price: 59.99,
    cost: 28.0,
    quantity: 0,
    minStock: 25,
    status: "out_of_stock",
    description: "Classic fit denim jeans",
    image: "👖",
    createdAt: "2025-09-10",
  },
  {
    id: "prod-5",
    name: "Organic Green Tea (50 bags)",
    sku: "OGT-005",
    categoryId: "cat-3",
    supplierId: "sup-3",
    price: 12.99,
    cost: 5.5,
    quantity: 89,
    minStock: 30,
    status: "in_stock",
    description: "Premium organic green tea",
    image: "🍵",
    createdAt: "2025-11-28",
  },
  {
    id: "prod-6",
    name: "Premium Coffee Beans (1kg)",
    sku: "PCB-006",
    categoryId: "cat-3",
    supplierId: "sup-3",
    price: 24.99,
    cost: 12.0,
    quantity: 12,
    minStock: 20,
    status: "low_stock",
    description: "Single-origin arabica coffee beans",
    image: "☕",
    createdAt: "2025-10-05",
  },
  {
    id: "prod-7",
    name: "Ergonomic Office Chair",
    sku: "EOC-007",
    categoryId: "cat-4",
    supplierId: "sup-4",
    price: 349.99,
    cost: 200.0,
    quantity: 24,
    minStock: 10,
    status: "in_stock",
    description: "Adjustable lumbar support office chair",
    image: "🪑",
    createdAt: "2025-08-22",
  },
  {
    id: "prod-8",
    name: "Wireless Keyboard & Mouse",
    sku: "WKM-008",
    categoryId: "cat-4",
    supplierId: "sup-4",
    price: 49.99,
    cost: 25.0,
    quantity: 67,
    minStock: 15,
    status: "in_stock",
    description: "Slim wireless keyboard and mouse combo",
    image: "⌨️",
    createdAt: "2025-11-10",
  },
  {
    id: "prod-9",
    name: "LED Desk Lamp",
    sku: "LDL-009",
    categoryId: "cat-5",
    supplierId: "sup-1",
    price: 39.99,
    cost: 18.0,
    quantity: 45,
    minStock: 12,
    status: "in_stock",
    description: "Adjustable brightness LED desk lamp",
    image: "💡",
    createdAt: "2025-12-05",
  },
  {
    id: "prod-10",
    name: "Indoor Plant Pot Set",
    sku: "IPS-010",
    categoryId: "cat-5",
    supplierId: "sup-3",
    price: 29.99,
    cost: 12.0,
    quantity: 5,
    minStock: 10,
    status: "low_stock",
    description: "Ceramic plant pot set of 3",
    image: "🪴",
    createdAt: "2025-10-18",
  },
];

export const activities: Activity[] = [
  {
    id: "act-1",
    type: "stock_in",
    message: "150 units of Wireless Headphones received",
    timestamp: "2026-03-12T10:30:00",
  },
  {
    id: "act-2",
    type: "low_stock",
    message: "Smart Watch Pro is running low (8 units left)",
    timestamp: "2026-03-12T09:15:00",
  },
  {
    id: "act-3",
    type: "product_added",
    message: "New product LED Desk Lamp added to inventory",
    timestamp: "2026-03-11T16:45:00",
  },
  {
    id: "act-4",
    type: "stock_out",
    message: "Denim Jeans sold out — reorder needed",
    timestamp: "2026-03-11T14:20:00",
  },
  {
    id: "act-5",
    type: "stock_in",
    message: "200 Cotton T-Shirts restocked",
    timestamp: "2026-03-10T11:00:00",
  },
];

export const dashboardStats: DashboardStats = {
  totalProducts: 225,
  totalValue: 487650,
  lowStockItems: 12,
  outOfStock: 3,
  monthlyRevenue: 52340,
  revenueChange: 12.5,
};

export const chartData = [
  { month: "Jan", revenue: 32000, stock: 180 },
  { month: "Feb", revenue: 38000, stock: 195 },
  { month: "Mar", revenue: 41000, stock: 210 },
  { month: "Apr", revenue: 45000, stock: 205 },
  { month: "May", revenue: 48000, stock: 220 },
  { month: "Jun", revenue: 52340, stock: 225 },
];

export const categoryChartData = categories.map((c) => ({
  name: c.name,
  value: c.productCount,
  color: c.color,
}));

export const sales: Sale[] = [
  {
    id: "sale-1",
    receiptNo: "PS-20260312-001",
    items: [
      {
        productId: "prod-1",
        productName: "Wireless Bluetooth Headphones",
        sku: "WBH-001",
        image: "🎧",
        quantity: 2,
        unitPrice: 79.99,
        subtotal: 159.98,
      },
      {
        productId: "prod-5",
        productName: "Organic Green Tea (50 bags)",
        sku: "OGT-005",
        image: "🍵",
        quantity: 3,
        unitPrice: 12.99,
        subtotal: 38.97,
      },
    ],
    subtotal: 198.95,
    tax: 23.87,
    discount: 0,
    total: 222.82,
    paymentMethod: "card",
    amountPaid: 222.82,
    change: 0,
    cashierName: "John Doe",
    createdAt: new Date().toISOString().split("T")[0] + "T09:15:00",
  },
  {
    id: "sale-2",
    receiptNo: "PS-20260312-002",
    items: [
      {
        productId: "prod-3",
        productName: "Cotton T-Shirt (Pack of 3)",
        sku: "CTS-003",
        image: "👕",
        quantity: 1,
        unitPrice: 34.99,
        subtotal: 34.99,
      },
    ],
    subtotal: 34.99,
    tax: 4.2,
    discount: 5,
    total: 34.19,
    paymentMethod: "cash",
    amountPaid: 50,
    change: 15.81,
    cashierName: "John Doe",
    createdAt: new Date().toISOString().split("T")[0] + "T10:42:00",
  },
  {
    id: "sale-3",
    receiptNo: "PS-20260312-003",
    items: [
      {
        productId: "prod-8",
        productName: "Wireless Keyboard & Mouse",
        sku: "WKM-008",
        image: "⌨️",
        quantity: 1,
        unitPrice: 49.99,
        subtotal: 49.99,
      },
      {
        productId: "prod-9",
        productName: "LED Desk Lamp",
        sku: "LDL-009",
        image: "💡",
        quantity: 1,
        unitPrice: 39.99,
        subtotal: 39.99,
      },
    ],
    subtotal: 89.98,
    tax: 10.8,
    discount: 0,
    total: 100.78,
    paymentMethod: "ewallet",
    amountPaid: 100.78,
    change: 0,
    cashierName: "Maria Santos",
    createdAt: new Date().toISOString().split("T")[0] + "T11:30:00",
  },
  {
    id: "sale-4",
    receiptNo: "PS-20260312-004",
    items: [
      {
        productId: "prod-6",
        productName: "Premium Coffee Beans (1kg)",
        sku: "PCB-006",
        image: "☕",
        quantity: 2,
        unitPrice: 24.99,
        subtotal: 49.98,
      },
    ],
    subtotal: 49.98,
    tax: 6,
    discount: 0,
    total: 55.98,
    paymentMethod: "cash",
    amountPaid: 60,
    change: 4.02,
    cashierName: "John Doe",
    createdAt: new Date().toISOString().split("T")[0] + "T13:05:00",
  },
  {
    id: "sale-5",
    receiptNo: "PS-20260312-005",
    items: [
      {
        productId: "prod-1",
        productName: "Wireless Bluetooth Headphones",
        sku: "WBH-001",
        image: "🎧",
        quantity: 1,
        unitPrice: 79.99,
        subtotal: 79.99,
      },
    ],
    subtotal: 79.99,
    tax: 9.6,
    discount: 0,
    total: 89.59,
    paymentMethod: "card",
    amountPaid: 89.59,
    change: 0,
    cashierName: "Maria Santos",
    createdAt: new Date().toISOString().split("T")[0] + "T14:20:00",
  },
];

export const hourlySalesData = [
  { hour: "8AM", sales: 120, transactions: 2 },
  { hour: "9AM", sales: 340, transactions: 5 },
  { hour: "10AM", sales: 280, transactions: 4 },
  { hour: "11AM", sales: 450, transactions: 7 },
  { hour: "12PM", sales: 620, transactions: 9 },
  { hour: "1PM", sales: 380, transactions: 6 },
  { hour: "2PM", sales: 503, transactions: 8 },
  { hour: "3PM", sales: 290, transactions: 4 },
  { hour: "4PM", sales: 410, transactions: 6 },
  { hour: "5PM", sales: 520, transactions: 7 },
];

export const monitoringMetrics: MonitoringMetrics = {
  todaySales: sales.reduce((sum, s) => sum + s.total, 0),
  todayTransactions: sales.length,
  avgOrderValue:
    sales.reduce((sum, s) => sum + s.total, 0) / Math.max(sales.length, 1),
  itemsSoldToday: sales.reduce(
    (sum, s) => sum + s.items.reduce((i, item) => i + item.quantity, 0),
    0
  ),
  salesChange: 18.4,
};
